## Slicing
For multi-dimensional arrays, we can use a comma to separate slices across each dimension.
The code below shows example slices of a 2-D NumPy array.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


## Argmin and argmax
In addition to accessing and slicing arrays, it is useful to figure out the actual indexes of the minimum and maximum elements. To do this, we use the np.argmin and np.argmax functions.

The np.argmin and np.argmax functions take the same arguments. The required argument is the input array and the axis keyword argument specifies which dimension to apply the operation on.
- using axis=0 meant the function found the index of the minimum row element for each column.
- When we used axis=1, the function found the index of the minimum column element for each row.
- Setting axis to -1 just means we apply the function across the last dimension. In this case, axis=-1 is equivalent to axis=1.

In [3]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1], dtype=int64)
array([2, 2, 0], dtype=int64)
array([1, 1, 1], dtype=int64)
